spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/mp-test
    username: root
    password: 192354...
    type: com.alibaba.druid.pool.DruidDataSource

    hikari:
      connection-test-query: 1
      ##空闲最小连接数
      minimum-idle: 5
      ## 连接池最大连接数
      maximum-pool-size: 15
      ## 此属性控制从池返回的连接的默认自动提交行为
      auto-commit: true
    loginUsername: admin
    loginPassword: admin

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    #    host: 192.168.2.62
    port: 6379
    #链接超时时间
    timeout: 50000
    jedis:
      pool:
        max-idle: 10
        max-active: 10000
        #阻塞等待时间
        max-wait: 5000
    database: 0
    password: 192354...

server:
  port: 9986



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kx.demo.*.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
