spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master，如果读者只是单数据源只需要注释掉slave相关配置即可，这里为了方便演示master与slave保持相同
      datasource:
        master:
          url: jdbc:mysql://47.111.15.40:3306/mp-test
          username: root
          password: 192354...
          driverClassName: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:postgresql://47.111.15.40:5432/mp-test
          username: postgres
          password: 192354...
          driverClassName: org.postgresql.Driver

    #    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-nameame: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://127.0.0.1:3306/mp-test
#    username: root
#    password: 192354...
    type: com.alibaba.druid.pool.DruidDataSource

    hikari:
      connection-test-query: 1
      ##空闲最小连接数
      minimum-idle: 5
      ## 连接池最大连接数
      maximum-pool-size: 50
      ## 此属性控制从池返回的连接的默认自动提交行为
      auto-commit: true

  main:
    allow-bean-definition-overriding: true

  redis:
#    host: 127.0.0.1
    host: 47.111.15.40
    port: 6379
    #链接超时时间
    timeout: 50000
    jedis:
      pool:
        max-idle: 10
        max-active: 10000
        #阻塞等待时间
        max-wait: 5000
    database: 0
    password: 192354...

server:
  port: 9986



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kx.demo.*.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
